Replace gorilla/mux to net/http in go for `over` handlers
overprotocol/chronos pull request #20
Opened 2024-10-23 05:22 UTC by syjn99

At [Prysm 5.1.1](https://github.com/prysmaticlabs/prysm/releases/tag/v5.1.1), gorilla mux was replaced to net/http in go 1.22. This change wasn't applied to the handlers in `over` package, so applied.

2024-10-23 12:43 UTC, gazzua requested changes
Need to remove `gorilla_mux` at deps.bzl

2024-10-24 00:34 UTC, syjn99 commented
@gazzua To my knowledge, `deps.bzl` should be modified by running gazelle only. I ran the following command:

```bash
$ bazel run //:gazelle -- update-repos -from_file=go.mod -to_macro=deps.bzl%prysm_deps -prune=true
```

but `gorilla_mux` didn't removed(and there are some other changes that we missed before). I thought that other modules depends on `gorilla/mux` implicitly, so gazelle did nothing on it. Could you review this one?

2024-10-24 03:21 UTC, gazzua commented
It was my misunderstanding that only the packages listed in go.mod were being managed
```
 go mod graph | grep gorilla/mux
github.com/getkin/kin-openapi@v0.61.0 github.com/gorilla/mux@v1.8.0
github.com/getkin/kin-openapi@v0.53.0 github.com/gorilla/mux@v1.8.0
github.com/go-kit/kit@v0.10.0 github.com/gorilla/mux@v1.7.3
github.com/openzipkin-contrib/zipkin-go-opentracing@v0.4.5 github.com/gorilla/mux@v1.7.3
github.com/openzipkin/zipkin-go@v0.2.2 github.com/gorilla/mux@v1.6.2
github.com/openzipkin/zipkin-go@v0.2.1 github.com/gorilla/mux@v1.6.2
github.com/openzipkin/zipkin-go@v0.1.6 github.com/gorilla/mux@v1.6.2
```
and still used by other library 👍

2024-10-24 03:21 UTC, gazzua approved these changes

2024-10-24 03:45 UTC, merged